// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaiBTAqGMCNeSmj3-lfQKye2hxYoPit44',
    appId: '1:351104755514:web:277e6f20e0b853e1a01203',
    messagingSenderId: '351104755514',
    projectId: 'study-ap',
    authDomain: 'study-ap.firebaseapp.com',
    storageBucket: 'study-ap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_V4-Y6XHRF1Ayh93lwIUzaFyUaw9HoYI',
    appId: '1:351104755514:android:bef93b8a7b23ce3fa01203',
    messagingSenderId: '351104755514',
    projectId: 'study-ap',
    storageBucket: 'study-ap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZZsuXuzmZE9gCI14zINTwaZ1MuwNS9k',
    appId: '1:351104755514:ios:da7838bb0cb4e749a01203',
    messagingSenderId: '351104755514',
    projectId: 'study-ap',
    storageBucket: 'study-ap.appspot.com',
    iosClientId: '351104755514-7roclnhka7ntrmno410fhsqouarbhitg.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTZZsuXuzmZE9gCI14zINTwaZ1MuwNS9k',
    appId: '1:351104755514:ios:da7838bb0cb4e749a01203',
    messagingSenderId: '351104755514',
    projectId: 'study-ap',
    storageBucket: 'study-ap.appspot.com',
    iosClientId: '351104755514-7roclnhka7ntrmno410fhsqouarbhitg.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
